config/routes.rb
Rails.application.routes.draw do
  resources :public_assets
  post "/public_asset_statuses", to: "public_asset_statuses#create"
  get "/rake_runner", to: "public_assets#rake_runner"
  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response

  root "public_assets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/asset_size_checker.rb
require "faraday"
require Rails.root.join("app/helpers/application_helper")

class AssetSizeChecker
  include ApplicationHelper

  attr_reader :asset

  def initialize(asset)
    @asset = asset
  end

  def compare
    response = Faraday.get(asset.url)
    current = response.body.bytesize
    expected = asset.latest_value

    notification = Notification.new(asset.id, asset.url)
    if expected == current
      nothing_to_do(notification, humanize_size(current), humanize_size(expected))
    elsif within_tolerance?(current, expected)
      PublicAssetStatus.create!(public_asset_id: asset.id, value: current)
      automatic_update(notification, humanize_size(current), humanize_size(expected))
    else
      action_required(notification, humanize_size(current), humanize_size(expected))
    end
  end

  def within_tolerance?(current, expected)
    tolerance = ENV["SIZE_TOLERANCE"].to_i
    current.between?(expected - tolerance, expected + tolerance)
  end

private

  def action_required(notification, current, expected)
    notification.title = "Action required"
    notification.color = "needs-attention"
    notification.value = "Expected size is *#{expected}* Actual size is *#{current}*. Please check this script and update the <#{ENV['PRODUCTION_URL']}/public_assets/#{notification.id}|latest value> when you're happy that the situation is resolved."

    notification
  end

  def automatic_update(notification, current, expected)
    notification.title = "Automatic update"
    notification.color = "other"
    notification.value = "Expected size was *#{expected}* Actual size is *#{current}*. The expected value has been automatically updated to the new actual size."

    notification
  end

  def nothing_to_do(notification, current, expected)
    notification.title = "Nothing to do"
    notification.color = "same"
    notification.value = "Expected size is *#{expected}* Actual size is *#{current}*."

    notification
  end
end

app/models/asset_version_checker.rb
require "faraday"

class AssetVersionChecker
  attr_reader :asset

  def initialize(asset)
    @asset = asset
  end

  def compare
    current = get_version(ENV["GITHUB_URL"], asset.source_version_regex)
    expected = get_version(asset.url, asset.hosted_version_regex)

    notification = Notification.new(asset.id, asset.url)
    if expected == current
      nothing_to_do(notification, current, expected)
    else
      action_required(notification, current, expected)
    end
  end

  def get_version(url, regex)
    response = Faraday.get(url)
    match_data = response.body.match(regex)
    match_data ? match_data.captures.first.to_i : nil
  end

private

  def action_required(notification, current, expected)
    notification.title = "Action required"
    notification.color = "needs-attention"
    notification.value = "<#{notification.url}|Source version> is *#{expected}* <#{ENV['GITHUB_URL']}|Our version> is *#{current}*. Please fix our version then update the <#{ENV['PRODUCTION_URL']}/public_assets/#{notification.id}|latest value>."

    notification
  end

  def nothing_to_do(notification, current, expected)
    notification.title = "Nothing to do"
    notification.color = "same"
    notification.value = "<#{notification.url}|Source version> is *#{expected}* <#{ENV['GITHUB_URL']}|Our version> is *#{current}*."

    notification
  end
end

app/models/notification.rb
class Notification
  attr_reader :id, :url
  attr_accessor :color, :title, :value

  def initialize(id, url)
    @id = id
    @url = url
  end

  def banner
    "<#{ENV['PRODUCTION_URL']}/public_assets/#{id}|Asset check>: <#{url}|#{url}>"
  end

  def priority_color(priority)
    case priority
    when "needs-attention"
      "#d4351c"
    when "same"
      "#00703c"
    else
      "#1d70b8"
    end
  end

  def message
    {
      "attachments": [
        {
          "fallback": banner,
          "pretext": banner,
          "color": priority_color(color),
          "fields": [
            {
              "title": title,
              "value": value,
              "short": false,
            },
          ],
        },
      ],
    }
  end
end

app/models/notifier.rb
require "slack-notifier"
require "json"

class Notifier
  def notify(notification)
    notifier = Slack::Notifier.new ENV["SLACK_WEBHOOK_URL"] do
      defaults channel: ENV["SLACK_CHANNEL"], username: ENV["SLACK_USERNAME"]
    end

    notifier.ping notification.message
  end
end

app/models/public_asset.rb
class PublicAsset < ApplicationRecord
  has_many :public_asset_statuses, dependent: :destroy

  validates :url, :validate_by, presence: true
  validates :url, url: true

  def validate_by_size?
    validate_by == "size"
  end

  def validate_by_version?
    validate_by == "version"
  end

  def latest_value
    public_asset_statuses.order(created_at: :desc).first.value
  end

  def self.sizes
    where(validate_by: "size")
  end

  def self.versions
    where(validate_by: "version")
  end
end

app/models/public_asset_status.rb
class PublicAssetStatus < ApplicationRecord
  belongs_to :public_asset

  validates :public_asset_id, presence: true
  validates :value, presence: true
end

app/models/url_validator.rb
class UrlValidator < ActiveModel::EachValidator
  def self.compliant?(value)
    uri = URI.parse(value)
    uri.is_a?(URI::HTTP) && uri.host.present?
  rescue URI::InvalidURIError
    false
  end

  def validate_each(record, attribute, value)
    unless value.present? && self.class.compliant?(value)
      record.errors.add(attribute, "is not a valid URL")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: ENV["USERNAME"], password: ENV["PASSWORD"]
end

app/controllers/public_asset_statuses_controller.rb
class PublicAssetStatusesController < ApplicationController
  def create
    @public_asset_status = PublicAssetStatus.new(public_asset_status_params)

    if @public_asset_status.save
      redirect_to public_asset_url(@public_asset_status.public_asset), notice: "Public asset status was successfully created."
    else
      redirect_to public_asset_url(@public_asset_status.public_asset), notice: "Record not created - invalid value."
    end
  end

private

  def public_asset_status_params
    params.require(:public_asset_status).permit(:public_asset_id, :value)
  end
end

app/controllers/public_assets_controller.rb
class PublicAssetsController < ApplicationController
  before_action :set_public_asset, only: %i[show edit update destroy]

  def index
    @public_assets = PublicAsset.all
  end

  def show
    @url = @public_asset.url
    statuses = @public_asset.public_asset_statuses

    dates = statuses.map(&:created_at)
    @labels = dates.map { |date| Date.parse(date.to_s).strftime("%d/%m/%Y") }
    @values = statuses.map(&:value)
  end

  def new
    @public_asset = PublicAsset.new
  end

  def edit; end

  def create
    @public_asset = PublicAsset.new(public_asset_params)

    if @public_asset.save
      redirect_to public_asset_url(@public_asset), notice: "Public asset was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @public_asset.update(public_asset_params)
      redirect_to public_asset_url(@public_asset), notice: "Public asset was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @public_asset.destroy!

    redirect_to public_assets_url, notice: "Public asset was successfully destroyed."
  end

  def rake_runner
    run_rake("public_assets:check_all_sizes")
    run_rake("public_assets:check_all_versions")

    redirect_to public_assets_url, notice: "Rake tasks run."
  end

private

  def set_public_asset
    @public_asset = PublicAsset.find(params[:id])
  end

  def public_asset_params
    params.require(:public_asset).permit(:url, :validate_by, :hosted_version_regex, :source_version_regex)
  end

  def run_rake(task)
    log_file = Rails.root.join("log/#{Rails.env}.log")

    Process.fork do
      exec("bin/rake #{task} --trace 2>&1 >> #{log_file}")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ActionView::Helpers::NumberHelper

  def humanize_size(size)
    if size < 1024
      "#{number_with_delimiter(size, delimiter: ',')} Bytes"
    else
      "#{number_to_human_size(size)} (#{number_with_delimiter(size, delimiter: ',')} Bytes)"
    end
  end
end

app/views/public_asset_statuses/_form.html.erb
<%= form_with(model: PublicAssetStatus.new) do |form| %>
  <%= form.hidden_field :public_asset_id, value: @public_asset.id %>

  <% current_value = @public_asset.public_asset_statuses.last.value if @public_asset.public_asset_statuses.any? %>

  <% if @public_asset.validate_by_version? %>
    <% hint = "Please give new version number." %>
  <% else %>
    <% hint = "Please give new size in Bytes without commas." %>
  <% end %>

  <div class="govuk-form-group">
    <div id="size-hint" class="govuk-hint">
      <%= hint %>
    </div>
    <%= form.number_field :value, value: current_value, class: "govuk-input" %>
  </div>

  <%= form.submit "Update", class: "govuk-button" %>
<% end %>

app/views/public_assets/_form.html.erb
<%= form_with(model: public_asset) do |form| %>
  <% if public_asset.errors.any? %>
    <div class="govuk-error-summary" data-module="govuk-error-summary">
      <div role="alert">
        <h2 class="govuk-error-summary__title">
          <%= pluralize(public_asset.errors.count, "error") %> prohibited this record from being saved:
        </h2>
        <div class="govuk-error-summary__body">
          <ul class="govuk-list govuk-error-summary__list">
            <% public_asset.errors.each do |error| %>
              <li><%= link_to error.full_message, "#public_asset_url" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>

  <%
    div_classes = ["govuk-form-group"]
    field_classes = ["govuk-input"]

    if public_asset.errors.any?
      div_classes << "govuk-form-group--error"
      field_classes << "govuk-input--error"
    end
  %>

  <div class="<%= div_classes.join(" ") %>">
    <%= form.label :url, class: "govuk-label govuk-label--m" %>
    <% if public_asset.errors.any? %>
      <p id="public_asset_url-input-error" class="govuk-error-message">
        <span class="govuk-visually-hidden">Error:</span> Enter a valid URL
      </p>
    <% end %>
    <%= form.text_field :url, value: @public_asset.url, class: field_classes.join(" ") %>
  </div>

  <div class="govuk-form-group">
    <%= form.label :validate_by, class: "govuk-label govuk-label--m" %>
    <%= form.select :validate_by, ["size", "version"], { selected: @public_asset.validate_by }, { class: "govuk-select" } %>
  </div>

  <% if @public_asset.validate_by_version? %>
    <div class="govuk-form-group">
      <%= form.label :hosted_version_regex, class: "govuk-label govuk-label--m" %>
      <div id="size-hint" class="govuk-hint">
        Please enter a regex which has a capture group for the version number of the GOV.UK maintained JavaScript file.
      </div>
      <%= form.text_field :hosted_version_regex, value: @public_asset.hosted_version_regex, class: "govuk-input" %>
    </div>

    <div class="govuk-form-group">
      <%= form.label :source_version_regex, class: "govuk-label govuk-label--m" %>
      <div id="size-hint" class="govuk-hint">
        Please enter a regex which has a capture group for the version number of the source JavaScript file as it appears on <a href="<%= ENV['GITHUB_URL'] %>" target="_blank">GitHub</a>.
      </div>
      <%= form.text_field :source_version_regex, value: @public_asset.source_version_regex, class: "govuk-input" %>
    </div>
  <% end %>

  <%= form.submit "Save", class: "govuk-button" %>
<% end %>

app/views/public_assets/_line_chart.html.erb
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div>
  <canvas id="line-chart"></canvas>
</div>

<script>
  const ctx = document.getElementById('line-chart');

  new Chart(ctx, {
    type: 'line',
    data: {
      labels: <%= raw labels %>,
      datasets: [
        {
          label: <%= raw url %>,
          data: <%= raw values %>,
          fill: true,
          borderColor: 'rgb(75, 192, 192)',
          tension: 0.1
        }
      ]
    }
  });
</script>

app/views/public_assets/_notice.html.erb
<% if notice %>
  <div class="govuk-panel govuk-panel--confirmation">
    <div class="govuk-panel__body">
      <%= notice %>
    </div>
  </div>
<% end %>

app/views/public_assets/edit.html.erb
<h1 class="govuk-heading-l">Edit</h1>

<%= render "form", public_asset: @public_asset %>

app/views/public_assets/index.html.erb
<%= render "notice", locals: { notice: notice } %>

<p class="govuk-body">
  <table class="govuk-table">
    <caption class="govuk-table__caption govuk-table__caption--m">Public assets</caption>
    <thead class="govuk-table__head">
      <tr class="govuk-table__row">
        <th scope="col" class="govuk-table__header">URL</th>
        <th scope="col" class="govuk-table__header">Current value</th>
        <th scope="col" class="govuk-table__header">Validate by</th>
        <th scope="col" class="govuk-table__header"></th>
      </tr>
    </thead>
    <tbody class="govuk-table__body">
      <% @public_assets.each do |public_asset| %>
        <tr class="govuk-table__row">
          <td scope="row" class="govuk-table__cell">
            <%= public_asset.url %>
          </td>
          <td class="govuk-table__cell">
            <% if public_asset.public_asset_statuses.any? %>
              <% current_value = public_asset.public_asset_statuses.last.value %>
              <% if public_asset.validate_by_size? %>
                <%= humanize_size(current_value) %>
              <% else %>
                <%= current_value %>
              <% end %>
            <% end %>
          </td>
          <td class="govuk-table__cell">
            <%= public_asset.validate_by %>
          </td>
          <td scope="row" class="govuk-table__cell">
            <%= link_to "Show", public_asset, class: "govuk-link" %>
            <% if public_asset.validate_by_version? %>
              | <%= link_to "Ours", ENV["GITHUB_URL"], target: :_blank, class: "govuk-link" %>
              | <%= link_to "Source", public_asset.url, target: :_blank, class: "govuk-link" %>
            <% else %>
              | <%= link_to "Open", public_asset.url, target: :_blank, class:  "govuk-link" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>

<%= link_to "Run checker tasks", rake_runner_path, class: "govuk-button", data: { module: "govuk-button" } %>

app/views/public_assets/new.html.erb
<h1 class="govuk-heading-l">New</h1>

<%= render "form", public_asset: @public_asset %>

app/views/public_assets/show.html.erb
<%= render "notice", locals: { notice: notice } %>

<span class="govuk-caption-m"><%= @public_asset.validate_by %></span>
<h1 class="govuk-heading-m"><%= @public_asset.url %></h1>

<div class="govuk-!-padding-bottom-9">
  <%= render "line_chart", labels: @labels.to_json, url: @url.to_json, values: @values %>
</div>

<p class="govuk-body">
  <%= link_to "Edit", edit_public_asset_path(@public_asset), class: "govuk-link" %>
  | <%= link_to "New", new_public_asset_path, class: "govuk-link" %>
  <% if @public_asset.validate_by_version? %>
    | <%= link_to "Ours", ENV["GITHUB_URL"], target: :_blank, class: "govuk-link" %>
    | <%= link_to "Source", @public_asset.url, target: :_blank, class: "govuk-link" %>
  <% else %>
    | <%= link_to "Open", @public_asset.url, target: :_blank, class: "govuk-link" %>
  <% end %>
  <br/>

  <%= button_to "Destroy", @public_asset, method: :delete, class: "govuk-button govuk-button--warning", data: { module: "govuk-button" } %>
</p>

<h2 class="govuk-heading-m">Update current value</h2>

<div>
  <%= render "public_asset_statuses/form", public_asset: @public_asset %>
</div>